FWGS/xash3d-fwgs

- engine/common/host.c
Pretty much just duplicated the code from the old engine. Defaults to 1 millisecond. Also made the description a little more descriptive.
> Add the 'sleeptime' cvar and behavior from the 'Old Engine'.

- engine/common/net_ws.c
Swapped out a `Host_Error` for a `Con_Printf`, to prevent jumping to the console and potentially preventing progress through game menus if the network is down.
> Prevented net send errors from triggering an entire host error

- engine/server/sv_game.c
I noticed this when attempting to load a corrupted server DLL. If the functions cannot be found in the DLL, the existing mempool pointer was overwritten without being freed the next time `SV_LoadProgs` was called.
> SV_LoadProgs: Fixed potential memory leak if function failed

- engine/common/hpak.c
- engine/common/model.c
- game_launch/wscript
There were a couple of out-of-range/post-free accesses going on, which caused the Mac build to crash when optimisations were turned on.
> Various: Fixed obscure crashes on Mac

- engine/server/sv_client.c
I found that when kicking bots in my own fork, the server would crash because it would attempt to send a net message to an invalid address. `SV_DropClient` has been changed so that the disconnect message is not sent if the client is a fake client.
> SV_DropClient: Prevented transmission to fake clients

- engine/client/cl_game.c
- engine/common/common.c
- engine/eiface.h
- engine/server/sv_game.c
IIRC GetGameDir() used to return full path of game (in very old non-steam HL 1.1.1.0), however this has changed since steam version of Half-Life. Current versions of GoldSrc only returns the gamedir.
This was also the behavior of old versions of Xash3D FWGS.
Also using void functions for stub breaks some MODs which call those functions and rely on the return value (such as Counter-Strike 1.6 regamedll). This fixes the problem.
> engine: GetGameDir should return gamedir only. Add proper stub functions for some engine APIs

- Documentation/opensource-mods.md
In [opensource-mods.md](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/opensource-mods.md), the entry [Half-Life: Induction](https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/opensource-mods.md#half-life-induction-1) contains links to projects that seem to be related to 'Half-Life: Invasion'. The mod title was probably meant to be 'Half-Life: Invasion'.
> Fixed mod title in Open Source mods documentation.

- engine/common/filesystem.c
I think .zip extension can cause trouble with performance penalty if:
1. user put zip-archive with game data to mod folder to unpack it(and not remove it).
2. existing mods already has zip-archives with some data.
And I think It's main reason why Quake 3 uses .pk3 extension for zip-archives.
> engine: common: filesystem.c: do not load zip-archives with zip extension as bullet proof.

- engine/client/cl_game.c
This fixes a minor bug where sounds played via pfnPlaySoundByNameAtLocation (mainly from viewmodel animations e.g. MP5) would be left where it was emitted in the world, rather than following the local player as it does in Goldsrc.
I'm unsure of any long-term issues, but it fixes this one issue in particular.
> engine: client: Fixed sounds emitted by viewmodel animations only playing at where they were emitted from in the world

- engine/client/cl_parse.c
This fixes fades that occur at the beginning of a map being a tad screwy as a result of the ref state not being updated with fresh values, which only happens when a frame is being rendered (loading happens to prevent that).
For this issue:
https://github.com/FWGS/xash3d-fwgs/issues/103
> engine: client: update the ref state before R_NewMap is called

- ref_gl/gl_dbghulls.c
- ref_gl/gl_sprite.c
Partially reverts https://github.com/FWGS/xash3d-fwgs/commit/341e440c0749db1817061f955e6710a154ee22df
Fixes the Windows build on Travis
> Fix 2 instances of void* pointer arithmetic

- engine/platform/sdl/events.c
- engine/platform/sdl/in_sdl.c
1. Do not disable SDL_JOYSTICK events. Disabling these events causes
game controller events to be disabled as well. Instead, filter these events out.
2. Fix button mapping (it was off by one).
> Fix SDL_GAMECONTROLLER handling

- engine/common/com_strings.h
- ref_gl/wscript
1. `libref_gles2_gl4es.so` -> `libref_gl4es.so` because this is what's passed to `R_LoadRenderer`.
2. Add `gl4es` to `DEFAULT_RENDERERS` so that `R_CollectRendererNames` finds it.
> gl4es: Fix `so` name and add to renderer collector

- scripts/makepak.py
This makes it much simpler to define a buildroot package for xash-extras
buildroot places various buildroot-internal dot files in the package build directory
> makepak.py: Skip all filenames starting with .

- engine/common/system.c
This was using the wrong define
E.g. `-dev 2 -help` output did not fit into it
> system.c: Fix `Sys_Warn/Error` text buffer sizes

- engine/client/cl_gameui.c
- engine/client/vgui/vgui_draw.c
- engine/common/lib_common.c
1. Do not append a trailing newline to the result of COM_GetLibraryError.
2. Fix call sites.
> Fix COM_LibraryError newline handling

- engine/client/ref_common.c
Previously R_CollectRendererNames left gaps in the `ref` subarrays.
This caused `R_Init` to fail in some cases because it iterates between `0` and `ref.numRenderers`.
> Fix R_CollectRendererNames

- .clang-format
This is more consistent with how xash3d formats its `if` and `switch` statements
> .clang-format: SpaceBeforeParens: Never

- engine/client/in_joy.c
- engine/client/input.h
- engine/client/keys.c
- engine/keydefs.h
- engine/platform/sdl/events.c
1. Adds separate D-Pad bindings so that they don't conflict with arrow keys on the keyboard (companion `mainui` PR https://github.com/FWGS/mainui_cpp/pull/40).
2. Fix trigger buttons (the thresholds were wrong).
3. Adds basic default mappings for gamepad buttons.
> Gamepad fixes

- game_launch/game.cpp
- game_launch/wscript
This option is useful when xash3d is launched externally by a script that performs additional setup.
> game_launch: Add a --disable-menu-changegame build option

- engine/platform/sdl/sys_sdl.c
If Sys_Error gets called on windows with dev parameter, for example here https://github.com/FWGS/xash3d-fwgs/blob/5e0a0765ce1f82869f9d7ff3ef731f834c4faab5/engine/common/host.c#L498
Engine will wait indefenetely until console window receiwes escape hotkey.
https://github.com/FWGS/xash3d-fwgs/blob/5e0a0765ce1f82869f9d7ff3ef731f834c4faab5/engine/common/system.c#L439
But this will never happen because Wcon wasn't initialized.
As a side effect, other xash instances won't receive any escape key events.
https://github.com/FWGS/xash3d-fwgs/blob/5e0a0765ce1f82869f9d7ff3ef731f834c4faab5/engine/platform/win32/con_win.c#L465
> platform: win32: sdl: Fix zombie processes after early Sys_Error on windows+sdl

- engine/server/sv_client.c
Also changing the OS type based on which platform engine was built on.
> server: mark TSource responses as connectionless 

- engine/client/s_load.c
Довольно удобная мера чтобы определять звуки, которые забыли запрекешить, и видеть, из-за какого конкретно файла произошло подвисание во время игры.
> engine: sound: warn about late precached sounds in developer mode

- engine/client/console.c
Фиксит баг, из-за которого все строки, разделенные символом переноса, рисовались на одном уровне друг поверх друга.
> engine: client: fixed height argument writing in Con_DrawStringLen

- common/cvardef.h
- engine/client/cl_game.c
- engine/client/cl_main.c
- engine/client/cl_mobile.c
- engine/client/cl_parse.c
- engine/client/cl_qparse.c
- engine/client/console.c
- engine/client/in_joy.c
- engine/client/in_touch.c
- engine/client/input.c
- engine/client/input.h
- engine/client/keys.c
- engine/client/s_main.c
- engine/client/vid_common.c
- engine/common/cmd.c
- engine/common/common.c
- engine/common/common.h
- engine/common/cvar.c
- engine/common/cvar.h
- engine/common/filesystem.c
- engine/common/host.c
- engine/common/hpak.c
- engine/common/identification.c
- engine/common/net_ws.c
- engine/common/tests.h
- engine/platform/linux/in_evdev.c
- engine/platform/linux/s_alsa.c
- engine/server/sv_cmds.c
- engine/server/sv_filter.c
[ ] Select CVars and commands to protect
[ ] Decide what to do with touch cvars/commands, probably should be filtered by default. Or allowed but with unprivileged mode flag
[ ] Testing, testing, testing!
> Tighten engine and client security: Implement cl_filterstuffcmd

- Documentation/opensource-mods.md
I recently moved mod branches source code from [malortie/halflife](https://github.com/malortie/halflife) to separate repositories.
The changes update the links to use the new repositories.
> Updated links in opensource-mods.md

- common/enginefeatures.h
- engine/common/gamma.c
Необходимая фича для реализации нормальной гамма-коррекции/освещения в моде с кастомным рендером.
Уже протестил это всё, мне удалось внутри игры получить картинку в линейном пространстве.
> engine: added feature flag ENGINE_LINEAR_GAMMA_SPACE

- scripts/waifulib/compiler_optimizations.py
Ловит некоторые ошибки в движке. При этом если не подключиться студией и загрузить какую-то карту игра вылезает без всяких ошибок. Если просто сидеть в меню, даже разглядывать там 3д модель персонажа, то не вылетает.
Когда подключаюсь к процессу в студии при переходе на карту там в начале ударяется в
Вызвано исключение по адресу 0x00007FF6632961BE в xash3d.exe: 0xC0000005: нарушение прав доступа при чтении по адресу 0x000011DA95AB5D2C.
`sv.time = svgame.globals->time = 1.0f;	// server spawn time it's always 1.0 second`
это в `qboolean SV_SpawnServer` в \engine\server\sv_init.c
Вызвано исключение: нарушение доступа для чтения.
aligned_beg было 0x11DA95A7D000.
И дальше там ещё другие ошибки начинаются в рендере, модели, спрайты...
> add /fsanitize=address for msvc (windows) when sanitize

- engine/client/cl_game.c
Looking at https://github.com/ValveSoftware/halflife/blob/master/cl_dll/hud_redraw.cpp:
```cpp
int CHud :: DrawHudString(int xpos, int ypos, int iMaxX, char *szIt, int r, int g, int b )
{
return xpos + gEngfuncs.pfnDrawString( xpos, ypos, szIt, r, g, b);
}
```
```cpp
int CHud :: DrawHudStringReverse( int xpos, int ypos, int iMinX, char *szString, int r, int g, int b )
{
return xpos - gEngfuncs.pfnDrawStringReverse( xpos, ypos, szString, r, g, b);
}
```
We can see that `pfnDrawString` and `pfnDrawStringReverse` are supposed to return width instead of new X position.
I checked the behavior by using current Half-Life `client.dll`. I sent `ShowMenu` message to draw this titles entry:
```
Team_Menu_Join_IG
{
\wa\db\yc\rd\wa\db\yc\rd\wa\db\yc\rd\wa\db\yc\rd\wa\db\yc\rd\wa\db\yc\rd\wa\db\yc\rd
} …
```
> engine: make pfnDrawString & pfnDrawStringReverse return width

- engine/client/cl_game.c
- engine/client/cl_securedstub.c
Mainly for loading DoD (latest Steam version). Besides VGUI2 and filesystem_stdio, DoD calls some `dst` functions which are given by the engine through `F` function. I used a new define to not break compatibility with current `GetClientAPI` export.
> engine: implement support for secured client dlls

- engine/common/masterlist.c
- engine/common/netchan.h
It is essentially the same as ms.xash.su but due to current situation, it is known to be blocked on some Ukrainian ISPs.
ms2.xash.su is retired for now.
> engine: masterlist: replace master server domain by mentality.rip

- engine/server/sv_save.c
Should fix XashXT bug described here https://github.com/SNMetamorph/PrimeXT/issues/10
But I'm not sure, will it break compatibility with old saves?
> engine: sv_save: added entity_state_t->startpos to save fields

- engine/common/common.h
- engine/eiface.h
- engine/server/server.h
- engine/server/sv_game.c
Add new undocumented GoldSrc eiface function, PEntityOfEntIndexAllEntities,
a bug-free version of PEntityOfEntIndex
Ref: https://github.com/ValveSoftware/halflife/issues/2272
> engine: server: make PEntityOfEntIndex bug-compatible with GoldSrc

- engine/common/filesystem.c
Do not load fucking zip anymore!
1. Some mods already has zip and rar archives with additional content.
2. Users can place many archives with game data to mod folder.
It will be better to load compressed zip archives with `.pk3` extention only as bullet proof.
> engine: common: filesystem.c: do not load archives with zip extention… again.

- Documentation/bug-compatibility.md
- engine/common/common.h
- engine/common/host.c
- engine/server/sv_game.c
* for now we only have GoldSrc bug compatibility, can be used for
games that require precise GoldSrc behaviour, like CSCZDS
* enabled with -bugcomp command line
> Introduce bug-compatibility levels

- filesystem/filesystem.c
Counter-Strike uses COM_ExpandFileName to get full path to filesystem_stdio. When reading liblist.gam, the engine will clear the search path and the root search path will be cleared. Set it as static so it will be excluded from clearing.
First patch to prepare for VGUI2 support.
> filesystem: set root directory as static

- .github/workflows/c-cpp.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> .github: workflows: update github actions.

- engine/client/vgui/vgui_draw.c
- engine/client/vgui/vgui_draw.h
- engine/platform/sdl/in_sdl.c
To syncronize VGUI and engine cursor state and avoid potential cursor problems (faced with one in PrimeXT)
> Updating VGUI cursor state when cursor changed from engine

- engine/client/cl_game.c
- engine/client/cl_main.c
- engine/client/cl_scrn.c
- engine/client/vgui/vgui_draw.c
- engine/client/vgui/vgui_draw.h
- filesystem/filesystem.c
- filesystem/filesystem.h
VGUI part of #947 
This PR introduces new `internal_vgui_support` key in `gameinfo.txt` that signals the engine to skip loading VGUI until the client.dll is loaded.
Linking vgui_support code into client.dll makes sense if game developer want to replace VGUI by something else, or include a specific version of it. Like PrimeXT uses ImGUI now by re-using VGUI support APIs, and tf15-client statically links with OpenVGUI to have same interface across all platforms.
cc @SNMetamorph @Velaron 
also cc @kungfulon, we need to decide on VGUI startup sequence. VGUI1 cannot be loaded after client.dll. In mods, VGUI1 can be called in C++ constructors, before API was initialized. I placed a check in SCR_VidInit so VGUI1 won't get loaded here.
> Internal vgui support rework

- engine/client/cl_tent.c
- engine/common/hpak.c
Now we can get rid of removing custom.hpk file in mainui, after changing player spray, because now it works as it should.
> Player custom decals fixes #2

- Documentation/extensions/expanded-common-structures.md
- common/com_model.h
To make porting mod to 64-bit less painful
> common: com_model: changed common structs reserved fields type to intptr_t

- engine/common/soundlib/snd_mp3.c
Mpg123 requires a lseek-like api, which can be used as `lseek(fd, 0, SEEK_END)` to get filesize. However, `FS_Seek` just returns 0 on success. 
It seems like media/gamestartup.mp3 cannot be loaded due to this inconsistency.
> filesystem: fix lseek for mpg123

- common/port.h
- engine/common/con_utils.c
- filesystem/VFileSystem009.cpp
- filesystem/dir.c
- filesystem/filesystem.c
- filesystem/filesystem_internal.h
- filesystem/pak.c
- filesystem/tests/caseinsensitive.c
- filesystem/wad.c
- filesystem/wscript
- filesystem/zip.c
- public/crtlib.c
- public/crtlib.h
- scripts/cirrus/build_freebsd.sh
- scripts/gha/build_linux.sh
- scripts/gha/build_win32.sh
- wscript
Completely replaces old FixFileCase hack, and sits on top of DIR searchpaths, only kicking in where we really need it.
Also has very minor optimizations that's not specific for this branch.
Preliminary benchmarks results (on Black Ops Redux mod):
|Runs (naive) | time to first frame | level load | client connect 
|-----|---------------------|------------|---------------
|1 | 0.671 | 0.28 | 0.21
|2|0.667|0.27|0.22
|3|0.664|0.28|0.22
|4|0.836|0.28|0.23
|5|0.636|0.30|0.21
|Runs (cache) | time to first frame | level load | client connect 
|-----|---------------------|------------|---------------
|1 | 0.639 | 0.22 | 0.16
|2|0.637|0.21|0.16
|3|0.648|0.23|0.15
|4|0.629|0.22|0.16
|5|0.628|0.22|0.16
On master branch this mod doesn't even load :)
TODO:
Fixes #883, #755
> Directory entries caching for case-insensetive filesystem emulation

- common/xash3d_types.h
- engine/common/sys_con.c
- engine/common/whereami.c
- engine/platform/irix/dladdr.c
- engine/platform/irix/dladdr.h
- engine/platform/irix/xash-exec
- engine/platform/posix/lib_posix.c
- engine/platform/posix/net.h
- engine/platform/posix/sys_posix.c
- engine/wscript
- public/build.c
- public/build.h
- public/buildenums.h
- public/xash3d_mathlib.h
- wscript
- xash-exec
This is a series of patches to get the Xash3D dedicated server compiling on SGI IRIX 6.5.22 through 6.5.30. The next steps will be to improve engine support to get the server functional.
> Preliminary support for SGI IRIX

- engine/platform/sdl/sys_sdl.c
Initialize functions calling was overriden by XASH_POSIX macro
> engine: platform: sdl: fixed psvita & nswitch platform initializing

- ref/gl/gl_opengl.c
- scripts/gha/build_psvita.sh
- scripts/gha/deps_psvita.sh
No clue why NPOT texture mipmaps stopped working, but they did and that is the cause of the visual glitches mentioned in the Discord.
This breaks the menu buttons though since they don't render correctly with NPOT textures disabled for some reason.
This also bumps vitaGL to a newer commit, though still not the latest one because the latest one has major issues with the texture loader.
> PSVita: disable NPOT textures, use newer vitaGL

- engine/client/cl_gameui.c
- engine/common/common.h
- engine/common/con_utils.c
- engine/common/host.c
- engine/server/server.h
- engine/server/sv_game.c
- engine/server/sv_init.c
- engine/server/sv_main.c
- public/crtlib.c
cc @mittorn @SNMetamorph @nekonomicon @Vladislav4KZ 
Despite this in general might fix a lot of bugs on many platforms, this still needs to be tested against random oddities, especially in mods that were made for Xash3D.
I only had a random issue where entity didn't get correct state after map reload (load any map in HL1, then load Hazard Course, and you'll fall out of the elevator). But calling `SV_DeactivateServer()` in place of `SV_UnloadProgs()` in `SV_Shutdown()` seems to be helped, and it makes sense to clean up entities, and etc.
> Disable server unload

- engine/client/ref_common.c
- engine/common/mod_bmodel.c
- ref/gl/gl_image.c
- ref/gl/gl_local.h
- ref/gl/gl_opengl.c
- ref/gl/gl_rmain.c
- ref/gl/gl_rmisc.c
- ref/gl/gl_rsurf.c
- ref/gl/gl_warp.c
We just update textures here.
This version differs from my older version I did for Yamagi Quake 2, just to be sure, I rechecked it with decompile and compared it against original `sw.dll`, that's why it uses only 64x64 despite drawing texture at 128x128.
I want this merged with the current CPU-based solution, as I believe someone smart will later make a GPU-based solution, and we would be able to compare if it will be any better.
> Software ripples for GL renderer

- engine/platform/linux/sys_linux.c
The `gettid()` library support was added in glibc 2.30. Earlier glibc versions did not provide a wrapper for this system call, necessitating the use of `syscall(2)`.
Also, put `_GNU_SOURCE` definition in the guard to avoid the warning:
```
../engine/platform/linux/sys_linux.c:16: warning: "_GNU_SOURCE" redefined
#define _GNU_SOURCE
<command-line>: note: this is the location of the previous definition
```
> engine: platform: linux: Add gettid definition for old systems

- engine/platform/sdl/in_sdl.c
- engine/platform/sdl/vid_sdl.c
When using SDL2 as the backend for input and video, the mouse cursor position is incorrect, leading to issues navigating menu ui or vguis with the mouse. This patch corrects the issue so the mouse cursor position matches the video output on high-dpi displays.
> fix incorrect mouse cursor position on high-dpi windows in SDL2 backend

- engine/client/cl_main.c
- engine/server/sv_init.c
- Fixed bug when `svs.testpacket_buf` was not being created on server at all
- Reduced overall server connection time (test probe delay reduced to 1.0 seconds)
- Count of test probes changed to 5, probe sizes are 64000, 32000, 10666, 5200, 1400
- Allowed to use bandwidth test on listen servers (why it even was disabled?)
- Fixed reconnection attempts after bandwidth test (they wasn't working as intended - just sending `bandwidth` packets instead of `getchallenge`)
> Connection bandwidth test fixes

- ref/gl/gl_image.c
> ref: gl: invalidate texture units state cache when texture deletes

- common/xash3d_types.h
- engine/common/zone.c
This cleans up 64-bit zone memory code, by reusing the same code for 32-bit and 64-bit platforms.
Now poolchain is a dynamically allocated array.
Rearranged data in `memheader_t` to avoid unnecessary padding on 64-bit.
> Realloc poolchain

- engine/common/crashhandler.c
I had this lying around since 2021. Might as well upload this, considering that MS is pushing hard for Windows on ARM devices.
These are the minimum required changes to make the codebase build for both ARM32 and ARM64 targets on Windows. Tested to work on both ARM and ARM64 targets.
References:
- [Overview of ARM64 ABI conventions](https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions)
- [Overview of ARM32 ABI Conventions](https://learn.microsoft.com/en-us/cpp/build/overview-of-arm-abi-conventions)
> Support building for Windows-on-ARM targets

- engine/client/cl_main.c
This can be pretty useful for statistical purposes and for tracking how many users using outdated/vulnerable Xash3D builds, and we can enforce such users to immediately update their Xash3D installation, for example. 
But masterserver should be updated to support such things too.
Reported information:
1. Xash3D version string
2. Build number
3. VCS commit hash
4. VCS branch name
5. Platform name
6. Architecture name
> More verbose reporting of engine build information to masterserver

- engine/client/ref_common.c
This is the first setting I change after installing xash3d-fwgs. Some distros even patch xash3d-fwgs to enable vsync by default (e.g. [Batocera](https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/ports/xash3d/xash3d-fwgs/0001-Enable-VSync-by-default.patch)).
Let's enable vsync by default here.
> Enable vsync by default

- common/r_efx.h
- engine/client/cl_efx.c
- ref/gl/gl_rpart.c
- ref/soft/r_part.c
Fixes messages spamming in mods such as Sven Co-op 4.8
> ref: disabled verbose reporting about tracer invalid color index

- engine/common/net_ws.c
- wscript
As a desperate attempt to have async resolve on platforms where POSIX threads aren't available.
In current version, SDL2 is preferred on all platforms where the SDL2 (i.e. full client) is enabled. I quickly tested it on Linux, and it works for me.
> Implement DNS resolve thread through SDL2 functions

- ref/gl/gl_studio.c
This restores the r_shadows cvar as it's also been re-enabled in HL25 and seems to be working fine.
> Restore r_shadows

- scripts/gha/build_apple.sh
This PR updates `build_apple.sh` to copy over SDL2 from `/Library/Frameworks`. SDL2 is installed in there by `dep_apple.sh`.
> gha: adds SDL2 to OSX builds (resolves #1791)

- ref/gl/gl_local.h
- ref/gl/gl_opengl.c
- ref/gl/gl_rmain.c
- ref/gl/gl_triapi.c
Some mods checking value of this cvar, and some Counter-Strike servers too.
> ref: gl: added gl_fog cvar for better GoldSrc compatibility

- common/bspfile.h
- common/com_model.h
- engine/client/cl_efrag.c
- engine/client/cl_render.c
- engine/client/cl_view.c
- engine/client/mod_dbghulls.c
- engine/client/ref_common.c
- engine/client/s_main.c
- engine/common/com_strings.h
- engine/common/mod_bmodel.c
- engine/common/mod_local.h
- engine/common/mod_studio.c
- engine/common/pm_surface.c
- engine/common/pm_trace.c
- engine/edict.h
- engine/ref_api.h
- engine/server/server.h
- engine/server/sv_game.c
- engine/server/sv_world.c
- ref/gl/gl_decals.c
- ref/gl/gl_rlight.c
- ref/gl/gl_rmain.c
- ref/gl/gl_rsurf.c
- ref/soft/r_bsp.c
- ref/soft/r_decals.c
- ref/soft/r_light.c
- ref/soft/r_local.h
- ref/soft/r_main.c
- ref/soft/r_rast.c
- wscript
This is tough. We basically split all extended structures into two versions, one with 16-bit fields for Q1BSP and HLBSP (including BSP30ext) and another with 32-bit fields for QBSP2.
What it does is allow us to use the same engine binary for all supported formats and letting custom renderers, like PrimeXT, finally support QBSP2 alongside classic BSP formats.
What it doesn't, however, allow is to re-use existing custom renderers from Half-Life 1. Most, if not all of them, will probably crash after reading world `model_t` and getting wrong offsets and pointers when QBSP2 map is loaded.
Running a simple benchmark didn't show any significant drop in performance.
> Loading BSP2 maps in a single binary

- engine/common/filesystem_engine.c
- engine/platform/sdl/sys_sdl.c
- scripts/waifulib/sdl2.py
- Looks for game data in SDL pref path (Application Support)
- Sets XASH3D_EXTRAS_PAK1 to SDL base path (Resources dir in App Bundle
- Added option to force search for SDL dylib via pkgconfig on Darwin instead of Framework (option for Mac Source Ports build process)
> Modifications for Mac App Bundle

- public/xash3d_mathlib.h
sizeof(*m) calculates size only the first row, which is wrong
affected: https://github.com/w23/xash3d-fwgs/pull/758/commits/1c5e793fcc1bd17bd2a03f2a64c6b02cab601c05
> Fix Matrix*x4_LoadIdentity (xash3d_mathlib.h)

- Documentation/supported-mod-list.md
~Also improved uplink setup and used a better source for mod files.~
> Documentation: Improve mod installation instructions

- engine/platform/sdl/events.c
- engine/platform/sdl/vid_sdl.c
In this PR we will do the next:
1. Let the platform decide where to put our fullscreen window instead of unconditionally putting it at (0,0)
2. Fix window save position on multimonitor configurations.
3. Enumerate video modes for display where our window is created instead of display index zero.
> Another attempt to fix multimonitor issues with SDL backend

- engine/common/host.c
- engine/common/net_ws.c
- engine/platform/platform.h
- engine/platform/win32/sys_win.c
There were reports about high CPU usage with high framerates, especially on the servers.
As it seems, it might've been caused by insufficient accuracy of `Platform_Sleep`, which only accepts milliseconds. If we imagine game running at 500+ FPS, `Platform_Sleep` instantly becomes useless.
With this PR, `sleeptime` cvar resolution changes from milliseconds down to microseconds.
> engine: platform: introduce for Platform_NanoSleep, to be used for better sleeping in between frames for lowering CPU usage

- engine/client/cl_main.c
Fixes #2060
Until we don't have a better way to determine path MTU, just lower the bandwidth test values.
> engine: client: lower the bandwidth test fragment sizes to 1400 and less, as using 64k, 32k and more is unreliable

- engine/client/cl_tent.c
Right now when you land a headshot, enemy will launch blood so high since blood height are scaled with damage.
This is different from goldsrc.
Below tested using M3 in CSCZ for worst case scenario.
Before:
After:
GoldSrc:
> engine: client: fix TE_BLOODSPRITE behaviour to GoldSrc

- scripts/gha/deps_psvita.sh
Because modern Ubuntu versions provides CMake 4.x from apt, and this version breaks a lot of stuff.
> Fix nightly builds for PS Vita

- common/defaults.h
> Enabled touch controls by default for Nintendo Switch & PS Vita

- engine/client/ref_common.c
- engine/platform/dos/vid_dos.c
- engine/platform/linux/vid_fbdev.c
- engine/platform/platform.h
- engine/platform/sdl1/vid_sdl1.c
- engine/platform/sdl2/vid_sdl2.c
- engine/ref_api.h
- **Purpose**: Allows renderers to fetch the native window handle for direct integration (e.g., Vulkan/D3D/Metal).  
- **Returns**: Opaque pointer to the platform-specific handle (`HWND`, `NSWindow*`, `X11 Window`, etc.).  
- **Unsupported platforms**: Returns `NULL`
- **Supported platforms**: SDL2 only now (WIN32, X11, WAYLAND, MACOS)
```c 
// Usage example (renderer-side):  
window_handle_t window_handle = ref_api->R_GetWindowHandle();  
if (window_handle.type == 0) {  
Com_Error(ERR_FATAL, "Window handle not supported on this platform");  
}  
// ... create surface/swapchain with the handle  
```
> ref_api: R_GetWindowHandle method

- CONTRIBUTING.md
Now that Microsoft GitHub joined to shove LLM down our throats, I think it's time to make a note about it's usage.
So far, there is absolutely zero AI generated issues or PRs, so it seems declaring that responsibility lies on the contributor is the most safe option, i.e. sending hallucinated patches or reports might get contributor banned but if it's verified by them it's shouldn't a big difference from normal human-made contributions.
> contributing: add a note about usage of LLM-based tools

- README.md
SDL2 is no longer available directly on Fedora as of Fedora 42. I believe this should also be true on RedHat EL but I'd like other user feedback there.
There are other minor problems, like manually needing to install libGL.i686 but we probably shouldn't have to explain all of that as it will be system dependent for the time being. Most people will probably want to build straight into the 64bit version which doesn't have this problem. 
Using either a Fedora system or a Fedora pet container (distrobox or docker), run the command to install dependencies and then proceed with the rest of the build instructions. The old instructions would fail in the installation process, and careless setup (only installing the `sdl2-compat-devel`, for example) could result in cryptic build failures. You would …
> Fix README for Fedora/RedHat Dependencies
