- engine/client/cl_game.c
- engine/client/cl_gameui.c
- engine/client/cl_main.c
- engine/client/s_vox.c
- engine/common/mod_bmodel.c
- engine/common/model.c
- engine/server/sv_game.c
- engine/server/sv_save.c
I found that certain log messages I was getting were not entirely clear, so I did a quick skim of the repo and updated some which I thought could do with more information.
> Made various log messages more informative

- wscript
As in title
Keep forward this amazing work.
Regards
> fixed taberror: inconsistent use of tabs and spaces in indentation

- wscript
Same as https://github.com/FWGS/hlsdk-xash3d/pull/116
> wscript: fix syntax

- engine/common/imagelib/img_png.c
> engine: common: imagelib: img_png.c: add a missing return statement.

- engine/platform/sdl/events.c
- See issue 143
- Tested on SDL2
- Untested on SDL1.2
> engine: platform: sdl: Fix mousewheel in SDL2

- engine/common/host.c
> engine: userconfig.d support from old engine

- .github/workflows/codeql-analysis.yml
Add file for integration with CodeQL
> add codeql-analysis.yml

- scripts/travis_android_deps.sh
- scripts/travis_linux_deps.sh
- scripts/travis_windows_deps.sh
Helps avoid the following error message:
> The job exceeded the maximum log length, and has been terminated.
(e.g. https://travis-ci.org/github/FWGS/xash3d-fwgs/jobs/751744736)
Fixes Android builds on Travis
> travis: unzip quietly

- .gitmodules
> Add gl4es submodule

- engine/platform/linux/sys_linux.c
> sys_linux.c: Increase buffer size for /proc/self/status

- engine/client/ref_common.c
- engine/common/com_strings.h
@glebm can you try this patch if #247 got fixed?
> engine: ref: try to bruteforce all available renderers if we're failed to load requested one

- engine/platform/sdl/events.c
- engine/platform/sdl/in_sdl.c
1. Process events from all game controllers.
2. Support controller hotplug.
> SDL GameController: Hotplug and multiple gamepads

- utils/mdldec/mdldec.c
There possible crash:
https://github.com/FWGS/xash3d-fwgs/blob/master/utils/mdldec/mdldec.c#L173
> utils: mdldec: better validity checks.

- common/com_model.h
- common/xash3d_types.h
- engine/client/cl_netgraph.c
- engine/client/client.h
- engine/client/in_touch.c
- engine/client/ref_common.c
- engine/client/s_main.c
- engine/client/sound.h
- engine/common/common.c
- engine/common/common.h
- engine/common/filesystem.c
- engine/common/mod_bmodel.c
- engine/common/mod_local.h
- engine/common/model.c
- engine/common/net_buffer.c
- engine/common/net_buffer.h
- engine/common/net_chan.c
- engine/common/zone.c
- engine/ref_api.h
- engine/server/server.h
- engine/server/sv_client.c
- ref_gl/gl_local.h
- ref_gl/gl_opengl.c
- ref_gl/gl_rsurf.c
- ref_soft/r_context.c
- ref_soft/r_local.h
This patch potentially fixes 64-bit incompatibility with mods.
Fixes https://github.com/FWGS/hlsdk-xash3d/issues/167 and https://github.com/FWGS/hlsdk-xash3d/issues/150
> Replace pool pointers by pool handles

- engine/client/cl_game.c
Fixes https://github.com/FWGS/xash3d-fwgs/issues/442
> engine: client: remove redundant index check

- common/com_model.h
- common/xash3d_types.h
- engine/client/client.h
- engine/client/in_touch.c
- engine/client/ref_common.c
- engine/client/s_main.c
- engine/client/sound.h
- engine/common/common.c
- engine/common/common.h
- engine/common/filesystem.c
- engine/common/mod_bmodel.c
- engine/common/mod_local.h
- engine/common/model.c
- engine/common/net_chan.c
- engine/common/zone.c
- engine/ref_api.h
- engine/server/server.h
- ref_gl/gl_local.h
- ref_gl/gl_opengl.c
- ref_gl/gl_rsurf.c
- ref_soft/r_context.c
- ref_soft/r_local.h
This patch potentially fixes 64-bit incompatibility with mods.
Fixes FWGS/hlsdk-xash3d#167 and FWGS/hlsdk-xash3d#150
> engine: replace pool pointer by pool handle

- engine/client/cl_scrn.c
- engine/client/client.h
> engine: backport some fixes from 0.19 

- engine/common/host.c
- engine/server/server.h
- engine/server/sv_game.c
- engine/server/sv_init.c
- engine/server/sv_main.c
- engine/server/sv_save.c
> engine: server: implemented instant game library loading

- engine/client/cl_main.c
Фикс очепяточки, в связи с пачкой последних коммитов
> engine: client: cl_main: fixed compilation error

- engine/client/cl_game.c
- engine/client/in_touch.c
- engine/client/input.c
- engine/client/input.h
- engine/client/vgui/vgui_draw.c
- engine/common/crashhandler.c
- engine/platform/sdl/events.c
- engine/platform/sdl/vid_sdl.c
- engine/vgui_api.h
- vgui_support/vgui_surf.cpp
> Draft: Rework mouse

- ref_soft/r_edge.c
- ref_soft/r_main.c
- ref_soft/r_rast.c
- ref_soft/r_scan.c
Исправления падений ref_soft при запуске уровней. Работает на x64, должно на x86
> Fix ref_soft for x64

- engine/common/net_encode.c
Fixes https://github.com/FWGS/xash3d-fwgs/issues/635
> engine: client: fix DT_TIMEWINDOW_* signedness

- utils/mdldec/smd.c
> utils: mdldec: add fixed uv coords support.

- engine/common/mod_bmodel.c
- public/xash3d_mathlib.h
- ref_gl/gl_rsurf.c
> engine: common: fixed lightmap shifting in Mod_CalcSurfaceExtents

- engine/platform/win32/con_win.c
> engine: platform: con_win: fixed console window visibility without developer mode (fix #818)

- engine/client/cl_frame.c
> engine: cl_frame: fixed segfault in CL_UpdatePositions

- engine/client/cl_game.c
- ref_gl/gl_rmain.c
- ref_soft/r_main.c
- ref_soft/r_triapi.c
> Fixed TriAPI WorldToScreen behavior to match GoldSrc

- engine/common/mod_bmodel.c
> engine: common: make blue-shift map detect more robust

- engine/server/sv_client.c
Made by @Mr0maks for old engine
> engine: fixed vulnerability in NAT bypass mechanism

- engine/client/cl_frame.c
To look player model in third person look smooth
> engine: client: enable interpolation of local player angles

- wscript
> removed the typo in wscript

- public/miniz.h
https://github.com/richgel999/miniz/releases/tag/3.0.0
https://github.com/richgel999/miniz/blob/master/ChangeLog.md
> public: update miniz to version 3.0.0 from upstream.

- filesystem/filesystem.c
Will help running Xash on Linux with old mods.
> filesystem: try to normalize linux gamedll path for liblist.gam

- engine/client/cl_game.c
- engine/client/cl_main.c
> engine: client: cl_game: fixed client VGUI API initialization

- engine/common/hpak.c
Including fix of bug that causes writing crap in custom.hpk
> engine: common: minor code fixes in hpak.c

- engine/client/cl_main.c
- engine/common/net_chan.c
- engine/common/netchan.h
> File downloading fixes

- Documentation/debugging-using-minidumps.md
- engine/common/crashhandler.c
- engine/common/host.c
> Added support for minidumps generating

- engine/client/cl_securedstub.c
- engine/common/net_buffer.c
- engine/common/net_encode.c
- public/xash3d_mathlib.c
- public/xash3d_mathlib.h
- ref/gl/gl_alias.c
- wscript
> Enable -Werror=strict-aliasing and fix strict aliasing issues

- Documentation/extensions/mp3-loops.md
- engine/common/soundlib/snd_main.c
- engine/common/soundlib/snd_mp3.c
- utils/run-fuzzer/wscript
> Add support for MP3 looping through custom ID3v2 tagging

- common/defaults.h
- engine/client/console.c
- engine/client/in_joy.c
- engine/common/launcher.c
- engine/common/sys_con.c
- engine/platform/platform.h
- engine/platform/psvita/sce_sys/livearea/contents/template.xml
- engine/platform/psvita/sys_psvita.c
In collaboration with @fgsfdsfgs
> PS Vita port patches

- engine/platform/win32/con_win.c
> engine: platform: win32: implemented attaching to existing console

- engine/common/protocol.h
Protocol limit, as it encoded as unsigned byte.
> engine: protocol: increase MAX_LIGHTSTYLES from 64 to 256

- ref/gl/gl_triapi.c
Fix https://github.com/FWGS/xash3d-fwgs/issues/1188
> ref: gl: Goldsrc compatible fog implementation

- engine/common/crashhandler.c
Probably also needs change for x86_64
> Changed register names for NetBSD x86

- utils/mdldec/smd.c
Must fix https://github.com/FWGS/xash3d-fwgs/issues/1444
This code is similar to https://github.com/ZeqMacaw/Crowbar/blob/master/Crowbar/Core/GameModel/SourceModel10/SourceSmdFile10.vb#L125
@SNMetamorph please test.
> utils: mdldec: smd.c: fix linear movement loss.

- utils/mdldec/qc.c
- utils/mdldec/smd.c
cc @SNMetamorph 
Need some testing.
> utils: mdldec: add boneweights support.

- Documentation/donate.md
- README.md
Requesting links, bank details, crypto addresses, etc who actively participate in engine development, or at least mentioned in `Documentation/ports.md`.
> Add sponsorship information

- engine/common/crashhandler.c
- engine/common/whereami.c
- wscript
I tried to build this on OpenBSD 7.4 but ran into a few errors, these patches allow it to build.
> Fix building on OpenBSD 7.4

- ref/gl/gl_rmain.c
- ref/soft/r_main.c
Attempt to fix https://github.com/FWGS/xash3d-fwgs/issues/1662
cc @Hedgefog
> ref: if the entity is opaque, check the renderfx too, it might become translucent

- engine/client/in_touch.c
Pull Request with microphone button texture here: https://github.com/FWGS/xash-extras/pull/17
> engine: client: in_touch.c: added voicechat touch button

- engine/client/in_touch.c
Screenshots are taken in 1280x720 resolution
> engine: client: in_touch.c: make the voicechat and spray buttons multiplayer only

- engine/common/com_strings.h
- scripts/sailfish/harbour-xash3d-fwgs.spec
Discussion in https://github.com/FWGS/xash3d-fwgs/issues/1703
> Bump engine version to 0.21

- engine/common/net_http.c
Use function pointers instead of enum.
Preliminary chunked transfer and compression support.
Set address resolving to AF_UNSPEC from AF_INET, allowing the use of IPv6.
> engine: rework how HTTP finite-machine works

- engine/platform/sdl/sys_sdl.c
> Fixed path calc for extras on Mac

- Documentation/opensource-mods.md
Moved to https://github.com/HL1-Mods-Reimplementations-and-Ports.
> Update reimplementations and ports links.

- engine/common/imagelib/img_main.c
Might be faster on Android cc @Velaron
> engine: imagelib: try to use FS_Search to bruteforce through supported image formats
